import type { Command } from '../types';

export class HelpCommand implements Command {
    execute(): string {
        return [
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "",
            "  Available Commands",
            "",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "",
            "**File System Commands:**",
            "  **ls**           List directory contents",
            "  **cd**           Change directory",
            "  **pwd**          Print working directory",
            "  **cat**          Display file contents",
            "",
            "**Information Commands:**",
            "  **whoami**       Display personal information and introduction",
            "  **experience**   Show professional work experience",
            "  **education**   Display educational background",
            "  **skills**       List technical skills and technologies",
            "  **projects**     Show portfolio projects with links",
            "  **social**       Display social media profiles",
            "",
            "**CV & Documents:**",
            "  **cv**           Manage curriculum vitae (use 'cv help' for options)",
            "",
            "**Navigation & Tools:**",
            "  **pages**        List and navigate to website pages",
            "  **tools**        Access available web tools",
            "",
            "**Content & Media:**",
            "  **quote**        Display an inspirational quote",
            "  **books**        Show reading collection with progress tracking",
            "",
            "**Customization:**",
            "  **theme**        Switch between light/dark theme",
            "  **colors**       Display theme color palettes",
            "",
            "**Entertainment:**",
            "  **games**        Play interactive terminal games",
            "",
            "**System Commands:**",
            "  **help**         Display this help message",
            "  **welcome**      Show welcome message",
            "  **echo**         Echo text back to terminal",
            "  **clear**        Clear terminal screen",
            "",
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
            "",
            "For detailed information about a specific command, use: **[command] help**",
            "",
            "Example: **cv help** or **games help**",
        ].join("\n");
    }
}
